server:
  port: 8080
spring:
  application:
    #应用的名称
    name: Eat
  datasource:
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/Eat?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&useSSL=false&allowPublicKeyRetrieval=true
      username: root
      password: 123456
  # 邮箱配置文件
  mail:
    # 配置发送邮件的邮箱地址
    username: lskoudai@foxmail.com
    # 授权码
    password: moswyaqyjdbhbaha
    # 配置SMTP发送邮件的服务器地址
    host: smtp.qq.com
    # 配置SMTP服务器端口，填465也行
    port: 587
    default-encoding: utf-8
    properties:
      mail:
        # 配置SSL 加密工厂
        smtp:
          auth: true
          starttls:
            # 本地测试，放开ssl
            enable: true
            #            required: false
            # linux 系统需要配置
        #            protocols: TLSv1.2
        # 开启debug模式
        debug: false

mybatis-plus:
  configuration:
    #在映射实体或者属性时，将数据库中表名和字段名中的下划线去掉，按照驼峰命名法映射
    #驼峰命名
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      id-type: ASSIGN_ID
Eat:
  #上传的临时文件存储路径
  #  path: ./src/main/resources/images
  path: C:\images\